# Generated by Django 4.1.3 on 2022-12-13 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionUsuariosApp', '0002_alter_proyecto_id_alter_proyectosusuarios_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.IntegerField(choices=[(0, 'SuperUsuario'), (1, 'Administrador')]),
        ),
    ]
