# Generated by Django 4.1.3 on 2022-12-13 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionUsuariosApp', '0003_alter_proyecto_id_alter_usuario_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
