# Generated by Django 4.1.3 on 2022-12-15 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionUsuariosApp', '0011_remove_proyectosusuarios_proyecto_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectosusuarios',
            name='proyectoid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionUsuariosApp.proyecto'),
        ),
        migrations.AlterField(
            model_name='proyectosusuarios',
            name='usuarioid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionUsuariosApp.usuario'),
        ),
    ]
